# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-18 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coteId', models.CharField(max_length=10, unique=True, verbose_name='类别编号')),
                ('coteName', models.CharField(max_length=30, verbose_name='类别名字')),
            ],
            options={
                'db_table': 'Cote',
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
            },
        ),
    ]
