# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-22 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotegory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50, verbose_name='折旧方法')),
            ],
            options={
                'verbose_name': '折旧方法',
                'verbose_name_plural': '折旧方法',
                'db_table': 'depreciation',
            },
        ),
    ]
