# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-22 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotegory', '0002_depreciation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartID', models.CharField(max_length=50, unique=True, verbose_name='卡片编号')),
                ('fixID', models.CharField(max_length=50, unique=True, verbose_name='固定资产编号')),
                ('fixname', models.CharField(max_length=50, verbose_name='固定资产名称')),
                ('cote', models.CharField(max_length=20, verbose_name='类别编号')),
                ('cotename', models.CharField(max_length=20, verbose_name='类别名称')),
                ('spmodels', models.CharField(max_length=50, null=True, verbose_name='规格型号')),
                ('serialnum', models.CharField(max_length=50, null=True, verbose_name='产品序列号')),
                ('fixadd', models.CharField(choices=[('A', '自购资产'), ('B', '其它资产')], max_length=20, verbose_name='资产来源')),
                ('date', models.DateField(verbose_name='开始使用日期')),
                ('user', models.CharField(max_length=20, verbose_name='使用人')),
                ('place', models.CharField(max_length=50, verbose_name='存放地点')),
                ('employ', models.CharField(choices=[('1', '在用'), ('2', '闲置'), ('3', '在途'), ('4', '已处置')], max_length=20, verbose_name='使用状况')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原值')),
                ('currency', models.CharField(max_length=10, verbose_name='币种')),
                ('year', models.CharField(default='5', max_length=200, verbose_name='折旧年限')),
                ('stmonth', models.DateField(verbose_name='开始折旧月份')),
                ('monmoney', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='月折旧额')),
                ('addZ', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='累计折旧')),
                ('JanZ', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='月折旧额')),
                ('ZhM', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='账面价值')),
                ('ZhZ', models.CharField(max_length=20, verbose_name='折旧状态')),
                ('Jing', models.TextField(default='5%', max_length=20, verbose_name='净残值率')),
                ('JingC', models.CharField(max_length=20, verbose_name='净残值')),
                ('JinS', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='进项税')),
                ('BZ', models.TextField(max_length=2000, null=True, verbose_name='备注')),
                ('demeth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotegory.Depreciation', verbose_name='折旧方法')),
            ],
            options={
                'verbose_name': '资产卡片',
                'verbose_name_plural': '资产卡片',
                'db_table': 'fixation',
            },
        ),
    ]
