# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-22 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixation',
            name='cote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotegory.Cote', verbose_name='类别编号'),
        ),
    ]
