# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-22 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixation', '0002_auto_20190122_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixation',
            name='cote',
            field=models.CharField(max_length=20, verbose_name='类别编号'),
        ),
        migrations.AlterField(
            model_name='fixation',
            name='cotename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotegory.Cote', verbose_name='类别名称'),
        ),
    ]
