# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-22 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixation', '0003_auto_20190122_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixation',
            name='JingC',
            field=models.CharField(max_length=20, null=True, verbose_name='净残值'),
        ),
        migrations.AlterField(
            model_name='fixation',
            name='ZhM',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='账面价值'),
        ),
        migrations.AlterField(
            model_name='fixation',
            name='cartID',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='卡片编号'),
        ),
        migrations.AlterField(
            model_name='fixation',
            name='fixID',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='固定资产编号'),
        ),
    ]
