# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-22 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixation', '0004_auto_20190122_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixation',
            name='JanZ',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='减值准备'),
        ),
    ]
